# Exploratory Data Analysis

In [29]:
# Library
import pandas as pd
import plotly.express as px
from typing import List

pd.set_option('display.max_columns', None)

## Loading the dataset

In [30]:

data = pd.read_csv("../data/tracks.csv", index_col=0)

# Merge the first row with the header, to make the dataset easier to work with
first_row = data.iloc[0].astype(str)
headers = data.columns.astype(str)
data.columns = [f"{h}_{r}" if h != r else h for h, r in zip(headers, first_row)]
data = data[1:].reset_index(drop=True)
data = data.iloc[1:]
data.head()

C:\Users\31640\AppData\Local\Temp\ipykernel_23684\3152345081.py:1: DtypeWarning: Columns (0: album, 1: album.1, 2: album.5, 3: album.6, 4: album.8, 5: album.12, 6: artist.5, 7: artist.7, 8: artist.8, 9: artist.9, 10: artist.11, 11: track.1, 12: track.2, 13: track.6, 14: track.7, 15: track.12, 16: track.15, 17: track.17) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/tracks.csv", index_col=0)

,album_comments,album.1_date_created,album.2_date_released,album.3_engineer,album.4_favorites,album.5_id,album.6_information,album.7_listens,album.8_producer,album.9_tags,album.10_title,album.11_tracks,album.12_type,artist_active_year_begin,artist.1_active_year_end,artist.2_associated_labels,artist.3_bio,artist.4_comments,artist.5_date_created,artist.6_favorites,artist.7_id,artist.8_latitude,artist.9_location,artist.10_longitude,artist.11_members,artist.12_name,artist.13_related_projects,artist.14_tags,artist.15_website,artist.16_wikipedia_page,set_split,set.1_subset,track_bit_rate,track.1_comments,track.2_composer,track.3_date_created,track.4_date_recorded,track.5_duration,track.6_favorites,track.7_genre_top,track.8_genres,track.9_genres_all,track.10_information,track.11_interest,track.12_language_code,track.13_license,track.14_listens,track.15_lyricist,track.16_number,track.17_publisher,track.18_tags,track.19_title
1,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,[],AWOL - A Way Of Life,7,Album,2006-01-01 00:00:00,NaN,NaN,"<p>A Way Of Life, A Collective of Hip-Hop from...",0,2008-11-26 01:42:32,9,1,40.0583238,New Jersey,-74.4056612,"Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...",AWOL,The list of past projects is 2 long but every1...,['awol'],http://www.AzillionRecords.blogspot.com,NaN,training,small,256000,0,NaN,2008-11-26 01:48:12,2008-11-26 00:00:00,168,2,Hip-Hop,[21],[21],NaN,4656,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1293,NaN,3,NaN,[],Food
2,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,[],AWOL - A Way Of Life,7,Album,2006-01-01 00:00:00,NaN,NaN,"<p>A Way Of Life, A Collective of Hip-Hop from...",0,2008-11-26 01:42:32,9,1,40.0583238,New Jersey,-74.4056612,"Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...",AWOL,The list of past projects is 2 long but every1...,['awol'],http://www.AzillionRecords.blogspot.com,NaN,training,medium,256000,0,NaN,2008-11-26 01:48:14,2008-11-26 00:00:00,237,1,Hip-Hop,[21],[21],NaN,1470,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,514,NaN,4,NaN,[],Electric Ave
3,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,[],AWOL - A Way Of Life,7,Album,2006-01-01 00:00:00,NaN,NaN,"<p>A Way Of Life, A Collective of Hip-Hop from...",0,2008-11-26 01:42:32,9,1,40.0583238,New Jersey,-74.4056612,"Sajje Morocco,Brownbum,ZawidaGod,Custodian of ...",AWOL,The list of past projects is 2 long but every1...,['awol'],http://www.AzillionRecords.blogspot.com,NaN,training,small,256000,0,NaN,2008-11-26 01:48:20,2008-11-26 00:00:00,206,6,Hip-Hop,[21],[21],NaN,1933,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1151,NaN,6,NaN,[],This World
4,0,2008-11-26 01:45:08,2008-02-06 00:00:00,NaN,4,6,NaN,47632,NaN,[],Constant Hitmaker,2,Album,NaN,NaN,"Mexican Summer, Richie Records, Woodsist, Skul...","<p><span style=""font-family:Verdana, Geneva, A...",3,2008-11-26 01:42:55,74,6,NaN,NaN,NaN,"Kurt Vile, the Violators",Kurt Vile,NaN,"['philly', 'kurt vile']",http://kurtvile.com,NaN,training,small,192000,0,Kurt Vile,2008-11-25 17:49:06,2008-11-26 00:00:00,161,178,Pop,[10],[10],NaN,54881,en,Attribution-NonCommercial-NoDerivatives (aka M...,50135,NaN,1,NaN,[],Freeway
5,0,2008-11-26 01:45:05,2009-01-06 00:00:00,NaN,2,4,"<p> ""spiritual songs"" from Nicky Cook</p>",2710,NaN,[],Niris,13,Album,1990-01-01 00:00:00,2011-01-01 00:00:00,NaN,<p>Songs written by: Nicky Cook</p>\n<p>VOCALS...,2,2008-11-26 01:42:52,10,4,51.895927,Colchester England,0.891874,Nicky Cook\n,Nicky Cook,NaN,"['instrumentals', 'experimental pop', 'post pu...",NaN,NaN,training,large,256000,0,NaN,2008-11-26 01:48:56,2008-01-01 00:00:00,311,0,NaN,"[76, 103]","[17, 10, 76, 103]",NaN,978,en,Attribution-NonCommercial-NoDerivatives (aka M...,361,NaN,3,NaN,[],Spiritual Level

## Checking completeness
We need to check the completeness of the data to see how "bad" the damage is

In [ ]:
# The following function 'missing_values_table' was sourced from a GitHub Gist.
# Author: clarissaache
# Gist URL: https://gist.github.com/clarissaache/completeness.py
# Date Accessed: May 10, 2026
def missing_values_table(df):
    ''' get the total count and % of NaN in a cute little table'''
    mis_val = df.isnull().sum()
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
        "There are " + str(mis_val_table_ren_columns.shape[0]) +
            " columns that have missing values.")
    return mis_val_table_ren_columns

In [32]:
missing_values_table(data)

Your selected dataframe has 52 columns.
There are 28 columns that have missing values.

                            Missing Values  % of Total Values
track.15_lyricist                   106263               99.7
track.17_publisher                  105311               98.8
track.10_information                104225               97.8
track.2_composer                    102904               96.6
artist.1_active_year_end            101199               95.0
artist.16_wikipedia_page            100993               94.8
track.4_date_recorded               100415               94.2
artist.13_related_projects           93422               87.7
artist.2_associated_labels           92303               86.6
track.12_language_code               91550               85.9
album.3_engineer                     91279               85.6
album.8_producer                     88514               83.1
artist_active_year_begin             83863               78.7
artist.8_latitude                    62030               58.2
artist.10_longitude                  62030               58.2
artist.11_members                    59725               56.0
track.7_genre_top                    56976               53.5
artist.9_location                    36364               34.1
album.2_date_released                36280               34.0
artist.3_bio                         35418               33.2
artist.15_website                    27318               25.6
album.6_information                  23425               22.0
album.12_type                         6508                6.1
album.1_date_created                  3529                3.3
album.10_title                        1025                1.0
artist.5_date_created                  856                0.8
track.13_license                        87                0.1
track.19_title                           1                0.0

This only shows the percentage of missin values across all rows, but not per individual song, album or artist

In [33]:
# Information we'd like to have

def count_empty(df, cols: List, id: str):
    """
    Function takes dataset, list of target columns and the column name of the ID
    :param df: dataset of type dataframe
    :param cols: list of columns of list type
    :param id: name of the column where the key identifier is of string type
    :returns: a summary of how the percentages of empty values per unique ID
    """
    if id == "index":
        key_id = df.groupby(df.index)[cols].first()
    else:
        key_id = df.groupby(id)[cols].first()
    null_counts = key_id.isna().sum()
    total_key_id = len(key_id)
    null_percentages = (null_counts / total_key_id) * 100
    summary = pd.DataFrame({
    'Empty (Count)': null_counts,
    'Empty (%)': null_percentages.round(2)
    })

    print(summary.sort_values('Empty (%)', ascending=False))

In [34]:
album_cols = [
    'album.1_date_created', 'album.2_date_released', 
    'album.3_engineer', 'album.6_information', 
    'album.7_listens', 'album.8_producer', 'album.9_tags', 
    'album.10_title', 'album.11_tracks', 'album.12_type'
]

artist_cols = [
    "artist.1_active_year_end", "artist.2_associated_labels",
    "artist.3_bio", "artist.5_date_created",
    "artist.6_favorites", "artist.8_latitude",
    "artist.9_location", "artist.10_longitude",
    "artist.11_members", "artist.12_name"
    
]

track_cols = [
    "track_bit_rate", "track.2_composer",
    "track.3_date_created", "track.4_date_recorded",
    "track.5_duration", "track.7_genre_top",
    "track.8_genres", "track.9_genres_all",
    "track.10_information",	"track.11_interest",
    "track.12_language_code", "track.13_license",
    "track.14_listens", "track.15_lyricist",
    "track.16_number", "track.17_publisher",
    "track.18_tags", "track.19_title"
    
]


count_empty(df = data, cols = album_cols, id = "album.5_id")
count_empty(df = data, cols = artist_cols, id = "artist.7_id")
count_empty(df = data, cols = track_cols, id = "index")

                       Empty (Count)  Empty (%)
album.3_engineer               12593      84.36
album.8_producer               12316      82.50
album.2_date_released           5438      36.43
album.6_information             3568      23.90
album.12_type                    916       6.14
album.1_date_created             461       3.09
album.10_title                     2       0.01
album.7_listens                    0       0.00
album.9_tags                       0       0.00
album.11_tracks                    0       0.00
                            Empty (Count)  Empty (%)
artist.1_active_year_end            16698      97.91
artist.2_associated_labels          16057      94.15
artist.8_latitude                   12803      75.07
artist.10_longitude                 12803      75.07
artist.11_members                   12647      74.16
artist.9_location                   10580      62.04
artist.3_bio                        10403      61.00
artist.5_date_created                 233       1.37
artist.6_favorites                      0       0.00
artist.12_name                          0       0.00
                        Empty (Count)  Empty (%)
track.15_lyricist              106263      99.71
track.17_publisher             105311      98.81
track.10_information           104225      97.80
track.2_composer               102904      96.56
track.4_date_recorded          100415      94.22
track.12_language_code          91550      85.90
track.7_genre_top               56976      53.46
track.13_license                   87       0.08
track_bit_rate                      0       0.00
track.3_date_created                0       0.00
track.11_interest                   0       0.00
track.9_genres_all                  0       0.00
track.8_genres                      0       0.00
track.5_duration                    0       0.00
track.14_listens                    0       0.00
track.16_number                     0       0.00
track.18_tags                       0       0.00
track.19_title                      1       0.00

## Exploring distributions
Engagement data could be really valuable. However, before visualising data such as favourites and comments, we'd like to know if there's enough data for us to work with. For this, we check the sparsity. Even though the rows aren't empty, they can still say "0"

In [47]:
fig1 = px.histogram(data, x="album.4_favorites", title = "Distribution of album favourites")
fig1.show()

fig2 = px.histogram(data, x="album_comments", title = "Distribution of album comments")
fig2.show()

fig3 = px.histogram(data, x="track.14_listens", title = "Distribution of track listens")
fig3.update_layout(yaxis_range=[0,6000])
fig3.show()

### Log transformation
As you can tell from the distribution of track listens, it's all super skewed. To combat this, we can apply a log transformation on the data.

In [ ]:
# The following function 'missing_values_table' was sourced from a GitHub Gist.
# Author: acssantos
# Gist URL: https://gist.github.com/acssantos/3108539189e60e4b059130259d21f5a9
# Date Accessed: May 12, 2026

import numpy as np
import plotly.graph_objects as go

def log_histogram(data_list, names=None, bins=None):
    """ Plot histogram in log scale bins
    
        It constructs the numpy histogram with logarithm of data
        and plots a bar graph with customized ticks and hover.
        
        The plotly library does not have the option of ploting logscale
        histograms.
        
        Params
        ------
        data_list: list[np.array]
            Array to construct histogram
        names: list[str]
            Names for legend of data. Optional
        bins: array
            Custom array of bin edges to construct the histogram count, 
            by default it uses 'doane' automatic method from numpy.
            Should consider the log of data.
        
        Returns
        -------
        fig: plotly.graph_objs._figure.Figure
            Figure objetct with the histogram plot. To visualize use: fig.show()
        bins: array 
            Return the bin edges.            
    """
    
    fig = go.Figure()
    if names is None:
        names = [None]*len(data_list)
    print(names)
    
    fig_data = []
    histograms = {}
    for i, data in enumerate(data_list):
        log_data = np.log1p(data)
        # log_data = data
    
        if bins is None and i == 0:
            counts, bins = np.histogram(log_data, bins='doane', density=False)
        else:
            counts, bins = np.histogram(log_data, bins=bins, density=False)
        
        center_bins = 0.5 * (bins[:-1] + bins[1:])
        
        # Percentage 
        counts = counts/np.sum(counts)
        
        histograms[names[i]] = counts
        #Custom data should be of shape [len(x), cols]
        real_bins = np.exp(bins)-1
        ranges = np.stack((real_bins[:-1], real_bins[1:]), axis=-1)
        
        fig.add_trace(go.Bar(x=center_bins, y=counts, name=names[i]))
        
        fig.update_traces(customdata=ranges,
                          hovertemplate=
                          "bin:%{customdata[0]:.3f} - %{customdata[1]:.3f}<br><b>Count(%):%{y:.3f}</b>")
        #fig_data.append(go.Bar(x=center_bins, y=counts, name=names[i])
        

    #fig = go.Figure(data=fig_data)
    fig.update_layout(
        xaxis = dict(
            tickmode = 'array',
            tickvals = bins[::2], 
            ticktext = np.round(np.exp(bins[::2]),0)
        )
    )
    # fig.update_layout(barmode='stack')
    return fig, bins, histograms

In [46]:
data["track.14_listens"] = pd.to_numeric(data["track.14_listens"], errors='coerce')

fig, bins, hists = log_histogram(data_list=[data["track.14_listens"].dropna().values], names=["Listens"])

fig.update_layout(
    title="Distribution of Track Popularity (Log Scale)",
    xaxis_title="Number of Listens",
    yaxis_title="Percentage of Tracks",
    template="plotly_white" # Optional: makes it look a bit cleaner
)

['Listens']