# Exploratory Data Analysis

In [1]:
# Library
import pandas as pd
import plotly.express as px

## Loading the dataset

In [ ]:

data = pd.read_csv("../data/tracks.csv")

# Merge the first row with the header, to make the dataset easier to work with
first_row = data.iloc[0].astype(str)
headers = data.columns.astype(str)
data.columns = [f"{h}_{r}" if h != r else h for h, r in zip(headers, first_row)]
data = data[1:].reset_index(drop=True)
data.head()

C:\Users\31640\AppData\Local\Temp\ipykernel_9688\2622869854.py:1: DtypeWarning: Columns (0: Unnamed: 0, 1: album, 2: album.4, 3: album.5, 4: album.7, 5: album.11, 6: artist.4, 7: artist.6, 8: artist.7, 9: artist.8, 10: artist.10, 11: track, 12: track.1, 13: track.5, 14: track.6, 15: track.11, 16: track.14, 17: track.16) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/tracks.csv")

,Unnamed: 0_nan,album_comments,album.1_date_created,album.2_date_released,album.3_engineer,album.4_favorites,album.5_id,album.6_information,album.7_listens,album.8_producer,...,track.10_information,track.11_interest,track.12_language_code,track.13_license,track.14_listens,track.15_lyricist,track.16_number,track.17_publisher,track.18_tags,track.19_title
0,track_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,...,NaN,4656,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1293,NaN,3,NaN,[],Food
2,3,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,...,NaN,1470,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,514,NaN,4,NaN,[],Electric Ave
3,5,0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4,1,<p></p>,6073,NaN,...,NaN,1933,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1151,NaN,6,NaN,[],This World
4,10,0,2008-11-26 01:45:08,2008-02-06 00:00:00,NaN,4,6,NaN,47632,NaN,...,NaN,54881,en,Attribution-NonCommercial-NoDerivatives (aka M...,50135,NaN,1,NaN,[],Freeway

## Checking completeness
We need to check the completeness of the data to see how "bad" the damage is

In [12]:
# The following function 'missing_values_table' was sourced from a GitHub Gist.
# Author: clarissaache
# Gist URL: https://gist.github.com/clarissaache/completeness.py (derived from the image)
# Date Accessed: May 10, 2026
def missing_values_table(df):
    ''' get the total count and % of NaN in a cute little table'''
    mis_val = df.isnull().sum()
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
        "There are " + str(mis_val_table_ren_columns.shape[0]) +
            " columns that have missing values.")
    return mis_val_table_ren_columns

In [13]:
missing_values_table(data)

Your selected dataframe has 53 columns.
There are 52 columns that have missing values.

                            Missing Values  % of Total Values
track.15_lyricist                   106264               99.7
track.17_publisher                  105312               98.8
track.10_information                104226               97.8
track.2_composer                    102905               96.6
artist.1_active_year_end            101200               95.0
artist.16_wikipedia_page            100994               94.8
track.4_date_recorded               100416               94.2
artist.13_related_projects           93423               87.7
artist.2_associated_labels           92304               86.6
track.12_language_code               91551               85.9
album.3_engineer                     91280               85.6
album.8_producer                     88515               83.1
artist_active_year_begin             83864               78.7
artist.10_longitude                  62031               58.2
artist.8_latitude                    62031               58.2
artist.11_members                    59726               56.0
track.7_genre_top                    56977               53.5
artist.9_location                    36365               34.1
album.2_date_released                36281               34.0
artist.3_bio                         35419               33.2
artist.15_website                    27319               25.6
album.6_information                  23426               22.0
album.12_type                         6509                6.1
album.1_date_created                  3530                3.3
album.10_title                        1026                1.0
artist.5_date_created                  857                0.8
track.13_license                        88                0.1
track.19_title                           2                0.0
artist.6_favorites                       1                0.0
artist.4_comments                        1                0.0
album.9_tags                             1                0.0
album.4_favorites                        1                0.0
album.7_listens                          1                0.0
album.5_id                               1                0.0
album.11_tracks                          1                0.0
album_comments                           1                0.0
track.3_date_created                     1                0.0
track.1_comments                         1                0.0
track_bit_rate                           1                0.0
set.1_subset                             1                0.0
set_split                                1                0.0
artist.7_id                              1                0.0
artist.12_name                           1                0.0
artist.14_tags                           1                0.0
track.11_interest                        1                0.0
track.9_genres_all                       1                0.0
track.8_genres                           1                0.0
track.6_favorites                        1                0.0
track.5_duration                         1                0.0
track.14_listens                         1                0.0
track.16_number                          1                0.0
track.18_tags                            1                0.0

## Exploring distributions
Engagement data could be really valuable. However, before visualising data such as favourites and comments, we'd like to know if there's enough data for us to work with. For this, we check the sparsity. Even though the rows aren't empty, they can still say "0"

In [15]:
fig1 = px.histogram(data, x="album.4_favorites", title = "Distribution of album favourites")
fig1.show()

fig2 = px.histogram(data, x="album_comments", title = "Distribution of album comments")
fig2.show()